### In Startup.cs, ensure the following configured.
### services.AddOData(options => 
###    options.Select().Filter().OrderBy().Expand());

GET https://localhost:5001/WeatherForecast
Accept: application/json

### odata
GET https://localhost:5001/odata
Accept: application/json

### odata with meta. This will give the same as above
GET https://localhost:5001/odata
Accept: application/json;odata.metadata=full

### odata with meta none
GET https://localhost:5001/odata
Accept: application/json;odata.metadata=none

### odata metadata
GET https://localhost:5001/odata/$metadata
Accept: application/json

### odata people
GET https://localhost:5001/odata/people
Accept: application/json

### odata people with metadata
GET https://localhost:5001/odata/people
Accept: application/json;odata.metadata=minimal

### odata people with metadata full
GET https://localhost:5001/odata/people
Accept: application/json;odata.metadata=full

### odata people with metadata none
GET https://localhost:5001/odata/people
Accept: application/json;odata.metadata=none

### odata people 
GET https://localhost:5001/odata/$metadata#People
Accept: application/json

### odata people with metadata
GET https://localhost:5001/odata/$metadata#People
Accept: application/json;odata.metadata=full

### odata/vinylrecords
GET https://localhost:5001/odata/vinylrecords
Accept: application/json

### odata/vinylrecords with metadata
GET https://localhost:5001/odata/vinylrecords
Accept: application/json;odata.metadata=full

### odata/vinylrecords Metadata
GET https://localhost:5001/odata/$metadata#VinylRecords
Accept: application/json

### odata/people(1)
GET https://localhost:5001/odata/people(1)
Accept: application/json;odata.metadata=none

### odata/people(1) minimal metadata
GET https://localhost:5001/odata/people(1)
Accept: application/json;odata.metadata=minimal

### odata/people(1) minimal full
GET https://localhost:5001/odata/people(1)
Accept: application/json;odata.metadata=full

### odata/vinylrecords(1)
GET https://localhost:5001/odata/vinylrecords(1)
Accept: application/json;odata.metadata=none

### odata/vinylrecords(1) minimal metadata
GET https://localhost:5001/odata/vinylrecords(1)
Accept: application/json;odata.metadata=minimal

### odata/vinylrecords(1) full meta
GET https://localhost:5001/odata/vinylrecords(1)
Accept: application/json;odata.metadata=full

### odata/people(20). 20 does not exist
GET https://localhost:5001/odata/people(20)/Email
Accept: application/json

### odata/people(5). Try to get an UnexistingProperty
GET https://localhost:5001/odata/people(5)/UnexistingProperty
Accept: application/json

### odata/people(1). Try to get Email for people
GET https://localhost:5001/odata/people(1)/Email
Accept: application/json;odata.metadata=none

### odata/people(6). Try to get Email. 
### This person does not have email. 204 No Content will be the reposonse
GET https://localhost:5001/odata/people(6)/Email
Accept: application/json;odata.metadata=full

### odata/people(20). 20 does not exist
GET https://localhost:5001/odata/people(20)/Email/$value
Accept: application/json

### odata/people(5). Try to get an UnexistingProperty
GET https://localhost:5001/odata/people(5)/UnexistingProperty/$value
Accept: application/json

### odata/people(1). Try to get Email for people
GET https://localhost:5001/odata/people(1)/Email/$value
Accept: application/json;odata.metadata=none

### odata/people(6). Try to get Email. 
### This person does not have email. 204 No Content will be the reposonse
GET https://localhost:5001/odata/people(6)/Email/$value
Accept: application/json;odata.metadata=full

### odata/people(1). collection of properties(Vinyl Records) with full metadata
### This person does not have email. 204 No Content will be the reposonse
GET https://localhost:5001/odata/people(1)/VinylRecords
Accept: application/json;odata.metadata=full

### odata/people(1). collection of properties(Vinyl Records) with full metadata
### This person does not have email. 204 No Content will be the reposonse
GET https://localhost:5001/odata/people(1)/VinylRecords
Accept: application/json;odata.metadata=none


