@baseUrl = https://localhost:5001/odata

### GET service Def
GET {{baseUrl}} HTTP/1.1

### GET service Def
GET {{baseUrl}}/$metadata HTTP/1.1

### Get metatdata. Not sure what #Gadgets means here.
GET {{baseUrl}}#Gadgets HTTP/1.1
