### In Startup.cs, ensure the following configured.
### services.AddOData(options => 
###    options.Select().Filter().OrderBy().Expand());
### So here, select, filter and order by capability are added.
### Also at the endpoint, we need to add the attribute [EnableQuery]


## Do the following to give this a try.
## Start vs code in this folder(folder containing this start.http file)
## Start a terminal in vs code(Ctrl + Shift + `)
## Change directory to the api folder(cd .\OData0001010_Gadgets.Api\)
## Execute the command dotnet run to start the api.
## Ensure the api is running by browsing to https://localhost:5001/swagger/index.html
## Ensure the Rest Client extension is installed in Vs Code
## Now run the folliwng end points.


@baseUrl = https://localhost:5001/gadget/get/

### GET service Def
GET {{baseUrl}} HTTP/1.1

### Get metatdata. Not sure why this is not working. We need to add edm for this to work.
GET {{baseUrl}}?$metadata HTTP/1.1

### Select Name and cost
GET {{baseUrl}}?$select=ProductName,Cost HTTP/1.1
Accept: application/json

### Filter by product name
GET {{baseUrl}}?$filter=ProductName eq 'Pen Drive'
Accept: application/json

### Filter by cost
GET {{baseUrl}}?$filter=cost gt 900
Accept: application/json

### Filter by name starting with Head
GET {{baseUrl}}?$filter=Startswith(ProductName, 'Head')
Accept: application/json

### Filter by Product name in 
GET {{baseUrl}}?$filter=ProductName in ('Pen Drive', 'Head Phone')
Accept: application/json

### Order by 
GET {{baseUrl}}?$orderby=ProductName
Accept: application/json

### Order by desc
GET {{baseUrl}}?$orderby=ProductName desc
Accept: application/json
