### In Startup.cs, ensure the following configured.
### services.AddOData(options => 
###    options.Select().Filter().OrderBy().Expand());
### So here, select, filter and order by capability are added.
### Also at the endpoint, we need to add the attribute [EnableQuery]

## Do the following to give this a try.
## Start vs code in this folder(folder containing this start.http file)
## Start a terminal in vs code(Ctrl + Shift + `)
## Change directory to the api folder(cd .\OData6Demo.Api\)
## Execute the command dotnet run to start the api.
## Ensure the api is running by browsing to https://localhost:5001/swagger/index.html
## Ensure the Rest Client extension is installed in Vs Code
## Now run the folliwng end points.

### Select Name
GET https://localhost:5001/api/students?$select=name
Accept: application/json

### Select Name and id both
GET https://localhost:5001/api/students?$select=name, Id
Accept: application/json

### Filter by name
GET https://localhost:5001/api/students?$filter=name eq 'Vishu Goli'
Accept: application/json

### Filter by score
GET https://localhost:5001/api/students?$filter=score lt 165
Accept: application/json

### Filter by score again
GET https://localhost:5001/api/students?$filter=score gt 165
Accept: application/json

### Filter by name starting with S
GET https://localhost:5001/api/students?$filter=Startswith(Name, 'S')
Accept: application/json

### Filter by name in 
GET https://localhost:5001/api/students?$filter=Name in ('Sean Hobbs', 'Vishu Goli')
Accept: application/json

### Order by 
GET https://localhost:5001/api/students?$orderby=Name
Accept: application/json

### Order by desc
GET https://localhost:5001/api/students?$orderby=Name desc
Accept: application/json